### ISSUE TITLE
TODO voor gastcollegeversie 30 nov

### ISSUE THREAD

**Issue by maartenberg** [maartenberg/gitgud#2]
- [ ] Doemomenten eruit en omvormen naar geschreven opdrachten
- [ ] Meer uitleg over DAG (geschiedenis kan geen time-loops, verwijzingen naar voorganger)
- [ ] Meer hameren op edit-add-commit-cyclus
- [ ] reflog?
